package com.sample
global tools.Aircraft aircraft
global tools.TimePeriod timeperiod
global tools.Flightpath flightpath

import tools.*;
import dataobjects.*

 
 rule "Örtliche Filterung"
 	salience 10
 	when
 		m : AixmMessage ( location != flightpath.getDepatureAerodrome() && location != flightpath.getDestinationAerodrome())
 	
 	
 	then
 		System.out.println("not relevant at " + m.getScenario());
 		m.setRelevant(false);
 		retract(m);
 
 end
 
 
 rule "Zeitliche Filterung"
 	salience 11
 	when
 		m: AixmMessage ( endtime < timeperiod.getBeginPosition() || begintime > "27-Oct-2018" )  
 	then
 		System.out.println("not relevant Zeit " + m.getScenario());
 		m.setRelevant(false);
 		retract(m);
 end
 

