package com.sample
 

import tools.Aircraft;
 
rule "Test"
	when
		$a : Aircraft (wingSpan == 213.0)
		
		then
		System.out.println("rule erfolgreich"); 
end
 
/*rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end
*/
